service: aws-lamba-warming-spikes

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-2
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource:
        - 'Fn::Join':
          - ':'
          - - arn:aws:lambda
            - Ref: AWS::Region
            - Ref: AWS::AccountId
            - 'function:*'

plugins:
  - serverless-plugin-warmup

functions:
  hello:
    handler: handler.hello
    warmup: true

custom:
  warmup:
    enabled: true
    concurrency: 1
    prewarm: true
    schedule: rate(3 minutes)
    timeout: 60